IF(NOT ARNOLD_ROOT_DIR AND NOT $ENV{ARNOLD_ROOT_DIR} STREQUAL "")
  SET(ARNOLD_ROOT_DIR $ENV{ARNOLD_ROOT_DIR})
ENDIF()

SET(_ARNOLD_SEARCH_DIRS
  ${ARNOLD_ROOT_DIR}
  /usr/local
)

FIND_PATH(ARNOLD_INCLUDE_DIR
  NAMES         ai.h
  HINTS         ${_ARNOLD_SEARCH_DIRS}
  PATH_SUFFIXES include
)

FIND_LIBRARY(ARNOLD_LIBRARY
  NAMES         ai
  HINTS         ${_ARNOLD_SEARCH_DIRS}
  PATH_SUFFIXES bin
)

# handle the QUIETLY and REQUIRED arguments and set ARNOLD_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ARNOLD DEFAULT_MSG
    ARNOLD_LIBRARY ARNOLD_INCLUDE_DIR)

IF(ARNOLD_FOUND)
  SET(ARNOLD_LIBRARIES ${ARNOLD_LIBRARY})
  SET(ARNOLD_INCLUDE_DIRS ${ARNOLD_INCLUDE_DIR})
ENDIF(ARNOLD_FOUND)

MARK_AS_ADVANCED(
  ARNOLD_INCLUDE_DIR
  ARNOLD_LIBRARY
)

